name: Test
on:
  - push
  - pull_request

jobs:
  svgithub-test-job:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2
      - uses: WillAbides/setup-go-faster@v1.6.0
        with:
          go-version: 1.21.x
      - name: Get dependencies
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Run tests
        run: go test ./...
      - name: Run staticchecks
        run: staticcheck ./...
      - name: Run vet
        run: go vet ./...
